[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kagent-agw"
version = "0.1.0"
description = "Framework-specific integration points with kagent-sts"
requires-python = ">=3.11.0"
dependencies = [
  "kagent-core",
  "kagent-sts",
  "google-adk>=1.11.0",
  "google-genai>=1.21.1",
  "google-auth>=2.40.2",
  "httpx>=0.25.0",
  "pydantic>=2.5.0",
  "typing-extensions>=4.8.0",
  "aiofiles>=24.1.0",
  "anyio>=4.9.0",
]

[tool.uv.sources]
kagent-core = {workspace = true}
kagent-sts = {workspace = true}

[project.optional-dependencies]
test = [
  "pytest>=8.3.5",
  "pytest-asyncio>=0.25.3",
  "pytest-mock>=3.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/kagent"]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
