[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agw-sts-client"
version = "0.1.0"
description = "Security Token Service client implementing RFC 8693 OAuth 2.0 Token Exchange"
requires-python = ">=3.11.0"
dependencies = [
  "httpx>=0.25.0",
  "pydantic>=2.5.0",
  "typing-extensions>=4.8.0",
  "cryptography>=41.0.0",  # For JWT handling
  "PyJWT>=2.8.0",  # For JWT token parsing
]

[project.optional-dependencies]
test = [
  "pytest>=7.0.0",
  "pytest-asyncio>=0.21.0",
  "pytest-mock>=3.0.0",
]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.hatch.build.targets.wheel]
packages = ["src/agw_status_client"]
